baseDomain: example.com

clusterIssuer:
  enabled: true
  name: letsencrypt-giantswarm-gateway
  email: accounts@giantswarm.io
  gateway: giantswarm-default

gatewayClasses:
  - name: giantswarm-default
    overrideExternalDnsHostname: ""

gateways:
  - name: giantswarm-default
    tls:
      issuer: letsencrypt-giantswarm-gateway
    listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      hostname: example.{{ $.Values.baseDomain }}
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certSecretName: giantswarm-default-tls
