{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: {{ .Values.clusterIssuer.gateway }}
            namespace: {{ .Release.Namespace }}
{{- end }}
