{{- range $i, $class := .Values.gatewayClasses }}
{{- if $class.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gatewayclass-{{ $class.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                  - name: envoy
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                      readOnlyRootFilesystem: true
                  - name: shutdown-manager
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                      readOnlyRootFilesystem: true
                  securityContext:
                    runAsGroup: 65534
                    runAsNonRoot: true
                    runAsUser: 65534
                    seccompProfile:
                      type: RuntimeDefault
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $class.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: gatewayclass-{{ $class.name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
