{{- range $i, $gateway := .Values.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  {{- with $gateway.tls }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .clusterIssuer.name }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.className }}
  listeners:
    {{- range $gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- with .allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostname: {{ with .hostname }}{{ tpl . $ }}{{- end }}
      {{- with .tls }}
      tls:
        mode: {{ .mode }}
        {{- with .certSecretName }}
        certificateRefs:
        - kind: Secret
          name: {{ default (printf "le-%s" $gateway.name) . }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
